export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL";

export const USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAIL = "USER_SIGNUP_FAIL";

export const USER_LOGOUT = "USER_LOGOUT";

export const USER_FORGET_PASSWORD_REQUEST = "USER_FORGET_PASSWORD_REQUEST";
export const USER_FORGET_PASSWORD_SUCCESS = "USER_FORGET_PASSWORD_SUCCESS";
export const USER_FORGET_PASSWORD_FAIL = "USER_FORGET_PASSWORD_FAIL";

export const USER_NEW_PASSWORD_REQUEST = "USER_NEW_PASSWORD_REQUEST";
export const USER_NEW_PASSWORD_SUCCESS = "USER_NEW_PASSWORD_SUCCESS";
export const USER_NEW_PASSWORD_FAIL = "USER_NEW_PASSWORD_FAIL";

export const DELETE_ACCOUNT_REQUEST = "DELETE_ACCOUNT_REQUEST";
export const DELETE_ACCOUNT_SUCCESS = "DELETE_ACCOUNT_SUCCESS";
export const DELETE_ACCOUNT_FAIL = "DELETE_ACCOUNT_FAIL";
